src/AppBundle/Entity/Statistic.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(name="statistics")
 * @ORM\HasLifecycleCallbacks()
 * @ORM\Entity(repositoryClass="AppBundle\Repository\StatisticRepository")
 */
class Statistic
{
	/**
	 * @ORM\Id
	 * @ORM\Column(type="integer")
	 * @ORM\GeneratedValue(strategy="AUTO")
	 */
	public $id;

	/**
	 * @ORM\Column(type="string")
	 */
	public $website;

	/**
	 * @ORM\Column(type="integer")
	 */
	public $pagesAmount;

	/**
	 * @ORM\Column(type="integer")
	 */
	public $analysisTime;

	/**
	 * @ORM\Column(type="datetime")
	 */
	public $createdAt;

	/**
	 * @ORM\Column(type="datetime")
	 */
	public $updatedAt;

	public function __construct($website)
	{
		$this->website = $website;
		$this->createdAt = new \DateTime();
		$this->updatedAt = new \DateTime();
	}

	/**
	 * @ORM\PreUpdate()
	 */
	public function setUpdatedAtValue()
	{
		$this->updatedAt = new \DateTime();
	}

	public function getAnalysisTimeFormatted()
	{
		return gmdate("H:i:s", $this->analysisTime);
	}
}

src/AppBundle/Controller/MainController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Feedback;
use AppBundle\Entity\Progress;
use AppBundle\Form\FeedbackType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\StreamedResponse;

class MainController extends Controller
{
	/**
	 * @Route("/", name="homepage")
	 * @Method({"GET", "POST"})
	 * @Template
	 * @param Request $request
	 * @return array|string|JsonResponse
     */
    public function indexAction(Request $request)
	{
		if ($request->getMethod() == 'GET') return [];

		$this->get('enqueue.producer')->sendEvent('crawler', [
            'url' => $request->get('url'),
            'user' =>  $this->get('session')->get('user')
        ]);

		return new JsonResponse();
	}

    /**
     * @Route("/about", name="about")
     * @Method({"GET"})
     * @Template
     */
    public function aboutAction(){}

	/**
	 * @Route("/result", name="result")
	 * @Method({"GET"})
	 * @Template
	 * @param Request $request
	 * @return array|Response
	 */
    public function resultAction(Request $request)
    {
    	$host = $request->get('url');
    	$statistic = $this->getDoctrine()->getRepository('AppBundle:Statistic')->findOneBy(['website' => $host]);
    	$brokenLinkQuery = $this->getDoctrine()->getRepository('AppBundle:BrokenLink')->findByHost($host);
		$pagination = $this->get('knp_paginator')->paginate($brokenLinkQuery, $request->query->getInt('page', 1), 20);

		return ['pagination' => $pagination, 'host' => $host, 'statistic' => $statistic];
    }

    /**
     * @Route("/csv", name="csv")
     * @Method({"GET"})
     * @param Request $request
     * @return StreamedResponse
     */
    public function csvAction(Request $request)
    {
        $data = $this->getDoctrine()->getRepository('AppBundle:BrokenLink')->findAllByHost($request->get('url'));
        $response = $this->get('app.report.generator')->getCsvReport($data);

        return $response;
    }

	/**
	 * @Route("/contacts", name="contacts")
	 * @Method({"GET", "POST"})
	 * @Template
	 * @param Request $request
	 * @return array|RedirectResponse
	 */
    public function contactsAction(Request $request)
    {
		$feedback = new Feedback();
		$form = $this->createForm(FeedbackType::class, $feedback);
		$form->handleRequest($request);

		if ($form->isSubmitted() && $form->isValid()) {
			$this->get('em')->persist($feedback);
			$this->get('em')->flush();

            $this->get('enqueue.producer')->sendEvent('mailer', serialize($feedback));
			$this->addFlash('success', 'successful_feedback');
			return $this->redirectToRoute('contacts');
		}

		return ['form' => $form->createView()];
    }

	/**
	 * @Route("/progress", name="progress")
	 * @Method({"GET"})
	 * @param Request $request
	 * @return JsonResponse
	 */
	public function getProgressAction(Request $request)
	{
		$user = $this->get('session')->get('user');
		$website = $request->get('url');

		$progress = $this->getDoctrine()
			->getRepository('AppBundle:Progress')
			->getProgress($user, $website);

		if ($progress == 0) {
			$result = ['progress' => Progress::STARTED];
		} elseif ($progress == 100) {
			$result = [
				'url' => $this->generateUrl('result', ['url' => $request->get('url')]),
				'progress' => Progress::FINISHED];
		} else {
			$result = [
				'progressPercentage' => $progress,
				'progress' => Progress::IN_PROGRESS];
		}

		return new JsonResponse($result);
	}

	/**
	 * @Route("/login", name="login")
	 * @Template()
	 * @Method({"GET", "POST"})
	 * @return array
	 */
	public function loginAction()
	{
		return [
			'last_username' => $this->get('security.authentication_utils')->getLastUsername(),
			'error'  => $this->get('security.authentication_utils')->getLastAuthenticationError()
		];
	}
}

src/AppBundle/Resources/views/Main/about.html.twig
{% extends '@App/layout.html.twig' %}

{% block title %}About{% endblock %}

{% block content %}
    <div class="container">
        <h1>About</h1>
        <p>Here you can check your website on broken links.<br>
           Enter your site address and get detailed information about links that has http responses different from 200.<br>
           Broken links to media are also analysed.
        </p>
    </div>
{% endblock %}

src/AppBundle/Resources/views/Main/contacts.html.twig
{% extends '@App/layout.html.twig' %}

{% block title %}Contacts{% endblock %}

{% block content %}

    <div class="container">
        <div class="col-md-6 col-md-offset-3 top-margined">
            <h2>Please send us your feedback</h2>

            {{ form_start(form) }}
                {% include '@App/@partials/form-success.html.twig' %}
                {{ form_widget(form) }}
                <button type="submit" class="btn btn-primary">Submit</button>
            {{ form_end(form) }}

        </div>
    </div>

{% endblock %}

src/AppBundle/Resources/views/Main/exception.html.twig
{% extends '@App/layout.html.twig' %}

{% block title %}Something went wrong{% endblock %}

{% block content %}

    <div class="container">
        <div class="col-md-6 col-md-offset-3 top-margined">
            <h2>Oops...</h2>
            <div>
                Something went wrong.<br>
                Please try again later.
            </div>
        </div>
    </div>

{% endblock %}

src/AppBundle/Resources/views/Main/index.html.twig
{% extends '@App/layout.html.twig' %}

{% block title %}404links.ru{% endblock %}

{% block content %}
    <div class="container">
        <div class="col-md-10 col-md-offset-1 wrapper top-margined" id="website-submit-form-container">
            <h1 class="col-md-6 col-md-offset-2 bottom-margined">Find all 404 links on your site</h1>
            <form id="website-submit-form" method="post" action="{{ path('homepage') }}">
                <div class="col-md-8">
                    <div class="form-group">
                        <input class="form-control" id="url" name="url" placeholder="Enter website">
                    </div>
                </div>
                <div class="col-md-2">
                    <button id="website-submit-form-button" type="submit" class="btn btn-primary submit">Submit</button>
                </div>
            </form>
        </div>

        {% include '@App/@partials/progress-bar.html.twig' %}
    </div>
{% endblock %}

src/AppBundle/Resources/views/Main/login.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block title %}Login{% endblock %}

{% block body %}
    <div class="login-page">
        <div class="container">
            <div class="form">
                <form class="login-form" action="{{ path('login') }}" method="post">
                    <input type="text" placeholder="username" id="username" name="_username"/>
                    <input type="password" placeholder="password" id="password" name="_password"/>
                    <button>login</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block stylesheets %}

{% endblock %}

src/AppBundle/Resources/views/Main/result.html.twig
{% extends '@App/layout.html.twig' %}

{% block title %}Result{% endblock %}

{% block content %}
    <div class="container">
        <h2>{{ host }}</h2>
        <p>Pages analysed: {{ statistic.pagesAmount }}<br>
            Analysis time: {{ statistic.analysisTimeFormatted }}</p>
        <a href="{{ path('csv', {'url' : host}) }}" class="btn btn-primary">Download CSV</a><br><br>

        {{ knp_pagination_render(pagination) }}

        <div class="table-responsive">
            <table class="table table-hover table-bordered">
                <tr class="active">
                    <th>Broken link</th>
                    <th>Page</th>
                    <th>Status</th>
                </tr>

                {% for link in pagination %}
                    <tr>
                        <td><a target="_blank" href="{{ link.link }}">{{ link.link }}</a></td>
                        <td><a target="_blank" href="{{ link.page }}">{{ link.page }}</a></td>
                        <td>
                            {% if link.status|slice(0, 1) == 4 %}
                                <button class="btn btn-warning btn-xs">{{ link.status }}</button>
                            {% else %}
                                <button class="btn btn-danger btn-xs">{{ link.status }}</button>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}

            </table>
        </div>

        {{ knp_pagination_render(pagination) }}

    </div>
{% endblock %}